baseURL = "https://tal.sdair.co.uk/"
languageCode = "en-gb"
title = "Today Alasdair Learned"
theme = "terminal"
Copyright = "© 2020 Alasdair Nicol | Terminal Theme by panr"

[languages]
  [languages.en]
    title = "Today Alasdair Learned"

    [languages.en.params.logo]
      logoText = "Today Alasdair Learned"
      logoHomeLink = "/"

[params]
  fullWidthTheme = false
  centerTheme = false
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "blue"
